#!/bin/bash

set -e   # Exit on any error
#set -x   # Uncomment for debug

function usage()
{
    echo "Usage: $(basename $0) [options]"
    echo
    echo "Options:"
    echo -e "\t--ext4"
    echo -e "\t\tUse mkfs.ext4"
    echo -e "\t--xfs"
    echo -e "\t\tUse mkfs.xfs"
    echo -e "\t-h, --help"
    echo -e "\t\tDisplay this help message and exit."
    exit 1
}

print_blue()
{
    echo -e "\e[01;34m$@\e[0m"
}

while [ $# -gt 0 ]; do
    case $1 in
        --ext4)
            FSTYPE=ext4
	    ;;
        --xfs)
	    FSTYPE=xfs
	    ;;
	--help|-h) usage $0; exit 0 ;;
	*)
            print_red "ERROR: Unrecognised argument: ${1}"
	    usage
	    ;;
    esac
    shift
done
if [ -z ${FSTYPE} ]; then
    FSTYPE=ext4
fi
print_blue "\nFile system type: ${FSTYPE}"

TEST_IMG=test.img
export TEST_DEV=/dev/loop0
export TEST_DIR=/mnt/test
SCRATCH_IMG=scratch.img
export SCRATCH_DEV=/dev/loop1
export SCRATCH_MNT=/mnt/scratch

if mount | grep -q ${TEST_DIR}; then
    sudo umount ${TEST_DIR}
fi
if mount | grep -q ${SCRATCH_MNT}; then
    sudo umount ${SCRATCH_MNT}
fi

sudo losetup -D

xfs_io -f -c "falloc 0 10g" ${TEST_IMG}
xfs_io -f -c "falloc 0 10g" ${SCRATCH_IMG}
mkfs.${FSTYPE} -f ${TEST_IMG}
#mkfs.${FSTYPE} -f -m rmapbt=1 ${TEST_IMG}
#mkfs.${FSTYPE} -f -m rmapbt=1 ${SCRATCH_IMG}
sudo losetup ${TEST_DEV} ${TEST_IMG}
sudo losetup ${SCRATCH_DEV} ${SCRATCH_IMG}
sudo mkdir -p ${TEST_DIR} && sudo mount ${TEST_DEV} ${TEST_DIR}
#sudo mkdir -p ${SCRATCH_MNT} && sudo mount ${SCRATCH_DEV} ${SCRATCH_MNT}
sudo mkdir -p ${SCRATCH_MNT}
